# Generated by Django 2.2.1 on 2019-05-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addGate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=7)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['complex'],
            },
        ),
    ]
