# Generated by Django 2.2.1 on 2019-05-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=5)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='media/sc/')),
            ],
        ),
    ]
