# Generated by Django 2.2.1 on 2019-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190516_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notip',
            options={'ordering': ['first']},
        ),
        migrations.AlterField(
            model_name='notip',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='sc'),
        ),
    ]
