# Generated by Django 2.2.1 on 2019-05-19 07:52

from django.db import migrations, models
import upload.validators


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190516_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='notip',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='notip',
            name='last',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='notip',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='sc', validators=[upload.validators.validate_file_size]),
        ),
    ]
