# Generated by Django 2.2.1 on 2019-05-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20190519_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='notip',
            name='repeat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notip',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
