# Generated by Django 2.2.1 on 2019-05-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_notip_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notip',
            old_name='author',
            new_name='user',
        ),
    ]
