# Generated by Django 2.2.1 on 2019-05-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_auto_20190523_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notip',
            name='user',
        ),
    ]
